# -*- coding: utf-8 -*-
"""rag_proje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RrLxAvU3ZSeNgfYtpUxMSQRX8MxpOhq4
"""

#*pip install faiss-cpu

import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
from transformers import pipeline

"""CSV'den veriyi yükleme"""

data=pd.read_csv("school_data.csv")
data.head()

"""Vektörlerin oluşturulması ve indeksleme"""

#* from sentence_transformers import SentenceTransformer
#* import faiss

#model yükleme
model=SentenceTransformer('all-MiniLM-L6-v2')

#veriyi hazırlama
corpus=data.apply(lambda row:f"{row['Ders Adı']} - {row['Açıklama']}",axis=1).tolist()

#vektörleri oluşturma
corpus_embeddings=model.encode(corpus)

#Faiss indeks oluşturma
index=faiss.IndexFlatL2(corpus_embeddings.shape[1])
index.add(corpus_embeddings)

print(f"İndekslenen kayıt sayısı: {index.ntotal}")

#*Sorgu İşleme -> Kullanıcıdan gelen soruyu vektörleştirelim ve en yakın sonuçları Faiss ile bulalım.

#Sorgu işlemi için fonksiyon
def search(query,k=1):
  #sorguyu vektörleştirme
  query_vector=model.encode([query])

  #Faiss ile en yakın komşuları arama
  distances, indices=index.search(query_vector,k)

  #Sonuçları derleme
  results=[]
  for idx in indices[0]:
    results.append(data.iloc[idx].to_dict())
  return results

#örnek sorgu:
"""query="programlama dillerine zaman?"
results=search(query)

for result in results:
  print(f"Ders: {result['Ders Adı']}, Tarih:{result['Sınav Tarihi']}, Öğretmen: {result['Öğretmen']}")
"""



